name: dev
channels:
  - defaults
  - dppy/label/dev
  - numba
  - intel
  - numba/label/dev
  - nodefaults
dependencies:
  - python=3.9
  - gxx_linux-64
  - dpcpp_linux-64
  - numba >=0.57*
  - dpctl >=0.14*
  - dpnp >=0.11*
  - mkl >=2021.3.0  # for dpnp
  - dpcpp-llvm-spirv
  - packaging
  - scikit-build
  - cmake
  - pytest
  - pip
  - pip:
    - coverage
    - pre-commit
    - flake8
    - black==20.8b1
    - pytest-cov
    - pytest-xdist
    - pexpect
variables:
  CHANNELS: -c defaults -c numba -c intel -c numba/label/dev -c dppy/label/dev --override-channels
  CHANNELS_DEV: -c dppy/label/dev -c defaults -c numba -c intel -c numba/label/dev --override-channels
