name: dev
channels:
  - defaults
  - numba
  - intel
  - numba/label/dev
  - dppy/label/dev
  - nodefaults
dependencies:
  - python=3.8
  - gxx_linux-64
  - dpcpp_linux-64
  - cython
  - numba 0.54*
  - dpctl >=0.10*
  - dpnp 0.7*=*_41
  - spirv-tools
  # - llvm-spirv 11.*
  - packaging
  - pytest
  - pytest-xdist
  - pip
  - pip:
    - pre-commit
    - flake8
    - black==20.8b1
    - pylint
variables:
  CHANNELS: -c defaults -c numba -c intel -c numba/label/dev -c dppy/label/dev --override-channels
  CHANNELS_DEV: -c dppy/label/dev -c defaults -c numba -c intel -c numba/label/dev --override-channels
