# Numba/llvmlite stack needs an older compiler for backwards compatibility.
c_compiler_version:         # [linux]
  - 7                       # [linux and x86_64]

cxx_compiler_version:       # [linux]
  - 7                       # [linux and x86_64]

dpctl:
  - 0.11.0

dpnp:
  - 0.9.0dev0=*_58

mkl:
  - 2021.3.0

pin_run_as_build:
  mkl: x.x
