name: GitHub Pages [Release, Tag]
on:
  push:
    branches:
      - release*
    tags:
      - '[0-9]+.[0-9]+*'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup numba-dpex
        uses: ./.github/actions/setup-develop
        with:
          environment: environment/docs.yml

      - name: Make documentation
        working-directory: docs
        run: make html

      - name: Publish release
        if: startsWith(github.ref, 'refs/heads/release')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir : next_release
          publish_dir: docs/_build/html/
          allow_empty_commit : true
          commit_message: ${{ github.event.head_commit.message }}


      - name: Capture tag
        id: capture_tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${GITHUB_REF#refs/heads/}"
          echo "${GITHUB_REF#refs/tags/}"
          echo ::set-output name=tag_number::${GITHUB_REF#refs/tags/}

      - name: Publish tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir : ${{ steps.capture_tag.outputs.tag_number }}
          publish_dir: docs/_build/html/
          allow_empty_commit : true
          commit_message: ${{ github.event.head_commit.message }}
