name: Test w/ Numba PRs

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pr: [7177, 7421]
      fail-fast: false

    env:
      ID: ${{ matrix.pr }}

    steps:
      - name: Checkout numba-dppy
        uses: actions/checkout@v2
        with: {path: numba-dppy}

      - name: Checkout numba
        uses: actions/checkout@v2
        with:
          repository: numba/numba
          path: numba

      # See https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
      - name: Checkout numba PR
        run: |
          cd numba
          git fetch origin pull/${{env.ID}}/head:pr${{env.ID}}
          git checkout pr${{env.ID}}

      - name: Add conda to system path
        shell: bash
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Configure environment
        run: |
          cd numba-dppy
          conda env update -n base -f environment.yml --prune

          conda list
          which python

      - name: Install numba
        run: |
          cd numba
          git log -1
          python setup.py develop

      - name: Install numba-dppy
        run: |
          cd numba-dppy
          git log -1
          python setup.py develop

      - name: Test installation
        run: |
          conda list

          python -c "import numba; print(numba.__file__)"
          python -c "import numba_dppy; print(numba_dppy.__file__)"

      - name: Test
        run: |
          # echo "libintelocl.so" | tee /etc/OpenCL/vendors/intel-cpu.icd
          export OCL_ICD_FILENAMES=libintelocl.so

          pytest -q -ra --disable-warnings --pyargs numba_dppy -vv
