name: Test w/ Numba PRs

on:
  workflow_dispatch:
    inputs:
      numba_pr:
        description: Numba PR
        required: true
        default: 7177

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ID: ${{ github.event.inputs.numba_pr }}

    steps:
      - name: Checkout numba-dpex
        uses: actions/checkout@v2
        with: {path: numba-dppy}

      - name: Checkout numba
        uses: actions/checkout@v2
        with:
          repository: numba/numba
          path: numba

      # See https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally
      - name: Checkout numba PR
        run: |
          cd numba
          git fetch origin pull/${{env.ID}}/head:pr${{env.ID}}
          git checkout pr${{env.ID}}

      - name: Add conda to system path
        shell: bash
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Configure environment
        run: |
          cd numba-dppy
          conda env update -n base -f environment.yml --prune
          conda remove -n base numba --force

          conda list
          which python

      - name: Install numba
        run: |
          cd numba
          git log -1
          python setup.py develop

      - name: Install numba-dpex
        run: |
          cd numba-dppy
          git log -1
          python setup.py develop

      - name: Test installation
        run: |
          conda list

          # echo "libintelocl.so" | tee /etc/OpenCL/vendors/intel-cpu.icd
          export OCL_ICD_FILENAMES=libintelocl.so

          python -c "import numba; print(numba.__file__)"
          python -c "import numba_dppy; print(numba_dppy.__file__)"

      - name: Test
        run: |
          # echo "libintelocl.so" | tee /etc/OpenCL/vendors/intel-cpu.icd
          export OCL_ICD_FILENAMES=libintelocl.so

          pytest -q -ra --disable-warnings --pyargs numba_dppy -vv
